### ISSUE TITLE
Replace `modal-1` with a more descriptive id

### ISSUE THREAD

**Issue by olleicua** [TheKnightsWhoSayNil/Camelot-Chess#38]
There are to references to it in the partial and one in the javascript:

https://github.com/TheKnightsWhoSayNil/Camelot-Chess/blob/master/app/views/partials/_modalforms.html.erb
https://github.com/TheKnightsWhoSayNil/Camelot-Chess/blob/master/app/assets/javascripts/modal.js

**Comment by olleicua** [comment]
Did you do this in a branch? I don't see the change

**Comment by BrandonElder** [comment]
Ah...yes.  I havn't merged my issues branch yet.  Will wait to close anything until I have done so.
