### ISSUE TITLE
There is a more concise way to use jQuery here

### ISSUE THREAD

**Issue by olleicua** [TheKnightsWhoSayNil/Camelot-Chess#39]
In this file: https://github.com/TheKnightsWhoSayNil/Camelot-Chess/blob/master/app/assets/javascripts/navbar.js

```javascript
  var more = document.getElementById("js-navigation-more");
  if ($(more).length > 0) {
```

could be written as

```javascript
  var more = $("#js-navigation-more");
  if (more.length > 0) {
```

and then on line 5 `$(more)` can simply be `more`

**Comment by BrandonElder** [comment]
Gotcha.  That's all Refills copy & pasting : /

**Comment by olleicua** [comment]
hmm.. I'm surprised. I always thought refills was higher quality..
