### ISSUE TITLE
Simplification in Games#show action

### ISSUE THREAD

**Issue by olleicua** [TheKnightsWhoSayNil/Camelot-Chess#40]
Lines 8 and 9 of this file

https://github.com/TheKnightsWhoSayNil/Camelot-Chess/blob/master/app/controllers/games_controller.rb

could be written more concisely as

```ruby
@black_player = @game.black_user
@white_player = @game.white_user
```

This is the benefit of the `belongs_to` statements in the Game model.

**Comment by olleicua** [comment]
Did you do this in a branch?

**Comment by Connerh92** [comment]
Yes, I closed so no one else would do more work than needed.. since I have done it already. I planned on pushing it with a few other issues...

**Comment by olleicua** [comment]
oh, ok.. I figured that because it was assigned to you nobody else would do
it..
