### ISSUE TITLE
It's a little confusing to have color be a boolean

### ISSUE THREAD

**Issue by olleicua** [TheKnightsWhoSayNil/Camelot-Chess#43]
One thing you could do is rename the column to be something like `is_white` and add a method to the model something like this:

```ruby
def color
  is_white ? :white : :black
end
```

**Comment by Connerh92** [comment]
got this changed to a color:string within the pieces table... so white just use 'WHITE' and black 'BLACK"... this was so confusing when trying to write the check method.

so anyways, this is changed now
