### ISSUE TITLE
instance variable would make more sense as plural `@games` in Games#index

### ISSUE THREAD

**Issue by olleicua** [TheKnightsWhoSayNil/Camelot-Chess#44]
line 17 in https://github.com/TheKnightsWhoSayNil/Camelot-Chess/blob/master/app/controllers/games_controller.rb

and line 6 in https://github.com/TheKnightsWhoSayNil/Camelot-Chess/blob/master/app/views/games/index.html.erb

**Comment by olleicua** [comment]
Did you do this one, is it in a branch?

**Comment by Connerh92** [comment]
yes got this changed
