### ISSUE TITLE
Questions about the pieces controller

### ISSUE THREAD

**Issue by olleicua** [TheKnightsWhoSayNil/Camelot-Chess#45]
These aren't all necessarily related but it seemed simpler to lump them into one issue:

1. on line 2  `, only: [:show, :update]` is redundant as those are the only actions defined on the controller
2. The routes file specifies that there is also a create action. Is that needed given that pieces are getting created in `Game#fill_board`
3. on line 5 `Piece.find_by_id(params[:id])` could be written more simply as `Piece.find(params[:id])`
4. It's not quite clear yet how the update action is meant to work but I'll assume that is because this is in progress

**Comment by tfreebern2** [comment]
1. Removed from Pieces Controller
2. :create removed from routes file
3. replaced with Piece.find(params[:id])
4. Update action completed. Working Test that redirects to game_path(game)
