### ISSUE TITLE
resource helpers are confusingly named

### ISSUE THREAD

**Issue by olleicua** [TheKnightsWhoSayNil/Camelot-Chess#46]
I would recommend renaming the helpers in this file:

https://github.com/TheKnightsWhoSayNil/Camelot-Chess/blob/master/app/helpers/application_helper.rb

It should be obviously what a method does by looking at its name.

**Comment by BrandonElder** [comment]
Yeah...makes sense to me but this is another thing I copy/pasted from (I believe) the devise tutorial.  Will renaming these effect anything else?

**Comment by olleicua** [comment]
I'm not sure. I'd take a look at the tutorial you git it from.

**Comment by BrandonElder** [comment]
So the names used in this helper file are called in the devise controller.  
[https://github.com/plataformatec/devise/blob/master/app/controllers/devise_controller.rb](url)
Should I still rename them & rename all instances of them being used in the controller?

**Comment by BrandonElder** [comment]
So the helper methods are used by Devise:
https://github.com/TheKnightsWhoSayNil/Camelot-Chess/blob/master/app/views/devise/sessions/new.html.erb
Would it make sense to rename the helper methods when it means that I would have to go through all of the devise forms where they are called and change those as well?  Or should I move the helper methods into a different file and just name it devise_helper.rb so at least it makes better sense what they are being used for?
