### ISSUE TITLE
adopt a consistent strategy for using `super` inside of `valid_move?`

### ISSUE THREAD

**Issue by olleicua** [TheKnightsWhoSayNil/Camelot-Chess#47]
One system that would work would be something like:

```ruby
class Piece
  def valid_move?(x, y)
    # return false if the move would be invalid for any piece type
    # return true otherwise
  end
end
```

```ruby
class Bishop
  def valid_move?(x, y)
    is_diagonal?(x, y) && !is_obstructed?(x, y) && super(x, y)
  end
end
```

It should be a consistent style for all of the pieces. `valid_move?` should always return a boolean

**Comment by kat-gie** [comment]
I think @lkcz04185 and I have both been using this:
 
  def valid_move?(x, y)
    super(x, y)
    # logic logic logic 
  end

Is that acceptable?

**Comment by olleicua** [comment]
It seems to work. It's confusing since the return statement is in another file but as long as your consistent it is fine with me.
