### ISSUE TITLE
notes on Queen#valid_move

### ISSUE THREAD

**Issue by olleicua** [TheKnightsWhoSayNil/Camelot-Chess#49]
1. It needs to call super
2.  `diagonal_move?`, `horizontal_move?`, and `vertical_move?` could be moved to piece.rb and then reused in rook.rb and bishop.rb.
3. whenever you see this

```ruby
def method
  if boolean_expression?
    return true
  end
  false
end
```

it can be simplified to

```ruby
def method
  boolean_expression?
end
```

**Comment by kat-gie** [comment]
Done!
