### ISSUE TITLE
King#valid_move can be simplified

### ISSUE THREAD

**Issue by olleicua** [TheKnightsWhoSayNil/Camelot-Chess#51]
Consider something like:

```ruby
class King
  def valid_move?(x, y)
    dx = (x_position - x).abs
    dy = (y_position - y).abs

    super(x, y) && dx <= 1 && dy <= 1
  end
end
```

**Comment by kat-gie** [comment]
Hope y'all don't mind, I was working on the castling and refactored the king's valid_move stuff 

  def valid_move?(x, y)
    super(x, y) && (valid_king_move?(x, y) || can_castle?(x,y))
  end 

  def valid_king_move?(x, y)
    dx = (x - x_position).abs
    dy = (y - y_position).abs
    dx <= 1 && dy <= 1 && dx + dy > 0
  end
