### ISSUE TITLE
Pawn#is_valid? can be simplified

### ISSUE THREAD

**Issue by olleicua** [TheKnightsWhoSayNil/Camelot-Chess#54]
Consider something like:

```ruby
class Pawn
  def valid_move?(x, y)

    if color == true
      move_range = 1
    else
      move_range = -1
    end

    if is_capture?
      super(x, y) && y == y_position + move_range && (x == x_position + 1 || x == x_position - 1)
    elsif in_starting_position?
      super(x, y) && y <= y_position + (move_range * 2) && x == x_position
    else
      super(x, y) && y <= y_position + move_range && x == x_position
    end
  end
end
```

Also `is_capture?` and `in_starting_position?` are wrong.

`is_capture?` should be something like:

```ruby
def is_capture?(x, y)
  game.pieces.find_by(x_position: x, y_position: y, color: !color).present?
end
```

and that could be defined in piece.rb

also `in_starting_position?` would probably be easiest to implement using a boolean column on the on the pieces table with a name like `has_moved` that is initially false and gets set to true whenever a piece gets moved.

**Comment by Connerh92** [comment]
We changed the color to a string, so it will be:
`if color == 'WHITE'`

**Comment by tfreebern2** [comment]
I rewrote the whole Pawn.rb file and found/fixed issues in the Pawn_spec.rb file as well.

All tests are passing.

Pawn.rb properly calls the super method and is consistent with other files in our app (King.rb, Queen.rb, etc).
